version: "3.7"
services:
  api-service:
    build: ./api-service
    tty: true
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./api-service:/api-service
      - /api-service/node_modules
    depends_on:
      - db-server

  line-service:
    build: ./line-service
    tty: true
    restart: always
    ports:
      - 3002:3000
    volumes:
      - ./line-service:/line-service
      - /line-service/node_modules

  db-server:
    container_name: db-server
    image: mysql:5.7.31
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
