version: "3.7"
services:
  api-server:
    build: .
    tty: true
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - .:/api-server
      - /api-server/node_modules
    depends_on:
      - db-server

  db-server:
    container_name: db-server
    image: mysql:5.7.31
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
